CREATE TABLE "user" (
  name varchar(255) NOT NULL,
  surname varchar(255) NOT NULL,
  email varchar(255) NOT NULL,
  phone varchar(255) NOT NULL,
  password varchar(255) NOT NULL,
  registrationTime date NOT NULL,
  profilePicture varchar(255) NULL,
  id_User bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY
);

CREATE TABLE administrator (
  id_User bigint PRIMARY KEY REFERENCES "user"(id_User)
);

CREATE TABLE broker (
  confirmed boolean NOT NULL,
  blocked boolean NOT NULL,
  id_User bigint PRIMARY KEY REFERENCES "user"(id_User)
);

CREATE TABLE buyer (
  confirmed boolean NOT NULL,
  blocked boolean NOT NULL,
  id_User bigint PRIMARY KEY REFERENCES "user"(id_User)
);

CREATE TABLE energyclass (
  id_EnergyClass integer PRIMARY KEY,
  name char(4) NOT NULL
);

INSERT INTO energyclass(id_EnergyClass, name) VALUES
(1,'A+++'),(2,'A++'),(3,'A+'),(4,'A'),(5,'B'),(6,'C'),(7,'D'),(8,'E'),(9,'F'),(10,'G');

CREATE TABLE finishtypes (
  id_FinishTypes integer PRIMARY KEY,
  name char(15) NOT NULL
);

INSERT INTO finishtypes(id_FinishTypes, name) VALUES
(1,'complete'),(2,'partial'),(3,'unfinished'),(4,'not fully built'),(5,'foundations'),(6,'other');

CREATE TABLE heatingtypes (
  id_HeatingTypes integer PRIMARY KEY,
  name char(10) NOT NULL
);

INSERT INTO heatingtypes(id_HeatingTypes, name) VALUES
(1,'central'),(2,'gas'),(3,'solid fuel'),(4,'electric'),(5,'heat pump'),(6,'other');

CREATE TABLE viewingstatus (
  id_ViewingStatus integer PRIMARY KEY,
  name char(9) NOT NULL
);

INSERT INTO viewingstatus(id_ViewingStatus, name) VALUES
(1,'pending'),(2,'confirmed'),(3,'rejected'),(4,'cancelled'),(5,'public');

CREATE TABLE session (
  id varchar(255) PRIMARY KEY,
  created date NOT NULL,
  remember boolean NOT NULL,
  lastActivity date NOT NULL,
  fk_Userid_User bigint NOT NULL REFERENCES "user"(id_User)
);

CREATE TABLE availability (
  "from" date NOT NULL,
  "to" date NOT NULL,
  id_Availability bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  fk_Brokerid_User bigint NOT NULL REFERENCES broker(id_User)
);

CREATE TABLE building (
  city varchar(255) NOT NULL,
  address varchar(255) NOT NULL,
  area double precision NOT NULL,
  year integer NOT NULL,
  lastRenovationYear integer NULL,
  floors integer NOT NULL,
  energy integer NULL REFERENCES energyclass(id_EnergyClass),
  id_Building bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  fk_Brokerid_User bigint NOT NULL REFERENCES broker(id_User)
);

CREATE TABLE confirmation (
  id varchar(255) PRIMARY KEY,
  expires date NOT NULL,
  fk_Buyerid_User bigint NOT NULL UNIQUE REFERENCES buyer(id_User)
);

CREATE TABLE apartment (
  apartmentNumber integer NULL,
  area double precision NOT NULL,
  floor integer NULL,
  rooms integer NOT NULL,
  notes varchar(10000) NULL,
  heating integer NULL REFERENCES heatingtypes(id_HeatingTypes),
  finish integer NOT NULL REFERENCES finishtypes(id_FinishTypes),
  id_Apartment bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  fk_Buildingid_Building bigint NOT NULL REFERENCES building(id_Building),
  isWholeBuilding boolean NOT NULL
);

CREATE TABLE viewing (
  "from" date NOT NULL,
  "to" date NOT NULL,
  status integer NOT NULL REFERENCES viewingstatus(id_ViewingStatus),
  id_Viewing bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  fk_Availabilityid_Availability bigint NOT NULL REFERENCES availability(id_Availability)
);

CREATE TABLE picture (
  id varchar(255) PRIMARY KEY,
  public boolean NOT NULL,
  fk_Apartmentid_Apartment bigint NOT NULL REFERENCES apartment(id_Apartment)
);

CREATE TABLE listing (
  description varchar(10000) NOT NULL,
  askingPrice double precision NOT NULL,
  rent boolean NOT NULL,
  id_Listing bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  fk_Viewingid_Viewing bigint NOT NULL UNIQUE REFERENCES viewing(id_Viewing),
  fk_Pictureid varchar(255) NOT NULL UNIQUE REFERENCES picture(id)
);