services:
  ntskelbimusistemasaitynai:
    image: ${DOCKER_REGISTRY-}ntskelbimusistemasaitynai
    build:
      context: .
      dockerfile: NTSkelbimuSistemaSaitynai/Dockerfile
    volumes:
      - ./NTSkelbimuSistemaSaitynai/storage/uploads:/app/storage/uploads
  frontend:
    build:
      context: frontend
      dockerfile: Dockerfile
      args:
        - VITE_API_BASE_URL=http://localhost:8080
    depends_on:
      - ntskelbimusistemasaitynai
  db:
    build:
      context: .
      dockerfile: PGSQLDockerfile

